import { Card, CardHeader } from '../ui/Card'
import { mockRecommendations } from '../../data/mockRecommendations'
import { AlertTriangle, CheckCircle2 } from 'lucide-react'
import { Link } from 'react-router-dom'
import clsx from 'clsx'

const ICON_BY_SEVERITY = {
  critical: { Icon: AlertTriangle, cls: 'text-danger' },
  warning: { Icon: AlertTriangle, cls: 'text-warn' },
  opportunity: { Icon: CheckCircle2, cls: 'text-brand' },
}

export function RecommendationFeed() {
  const items = mockRecommendations.slice(0, 3)
  return (
    <Card>
      <CardHeader
        title="Recommendations"
        subtitle="Generated by the analytics engine"
        actions={<Link to="/recommendations" className="text-[11px] text-brand hover:underline">View all</Link>}
      />
      <div className="divide-y divide-line">
        {items.map((r) => {
          const { Icon, cls } = ICON_BY_SEVERITY[r.severity]
          return (
            <div key={r.id} className="px-5 py-3.5 flex items-start gap-3">
              <Icon size={15} className={clsx('mt-0.5 shrink-0', cls)} />
              <div className="text-[12.5px] text-ink leading-relaxed">{r.title}</div>
            </div>
          )
        })}
      </div>
    </Card>
  )
}
