# Generated by Django 6.1.1 on 2026-09-15 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('machine_type', models.CharField(choices=[('CNC', 'CNC'), ('PRESS', 'Press'), ('CONVEYOR', 'Conveyor'), ('HVAC', 'HVAC'), ('ROBOT_ARM', 'Robot Arm'), ('COMPRESSOR', 'Compressor'), ('WELDING', 'Welding'), ('PACKAGING', 'Packaging')], max_length=50)),
                ('power_kw', models.FloatField()),
                ('operating_hours', models.FloatField()),
                ('utilization', models.FloatField()),
                ('heat_output', models.FloatField(default=0)),
                ('emission_factor', models.FloatField(default=0.72)),
                ('position_x', models.FloatField(default=0)),
                ('position_y', models.FloatField(default=0)),
                ('position_z', models.FloatField(default=0)),
                ('rotation_x', models.FloatField(default=0)),
                ('rotation_y', models.FloatField(default=0)),
                ('rotation_z', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='factory.factory')),
            ],
        ),
    ]
