# Generated by Django 6.1.1 on 2026-09-16 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0003_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines', to='factory.zone'),
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_type', models.CharField(choices=[('MATERIAL', 'Material Flow')], default='MATERIAL', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_connections', to='factory.machine')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='factory.factory')),
                ('source_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_connections', to='factory.machine')),
            ],
        ),
        migrations.CreateModel(
            name='EnergyReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('energy_kwh', models.FloatField()),
                ('power_kw', models.FloatField()),
                ('operating_hours', models.FloatField()),
                ('utilization', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_readings', to='factory.machine')),
            ],
        ),
    ]
