# Generated by Django 6.1.1 on 2026-09-16 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0004_machine_zone_connection_energyreading'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineTelemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('power_kw', models.FloatField()),
                ('utilization', models.FloatField()),
                ('operating_state', models.BooleanField(default=True)),
                ('production_units', models.FloatField(default=0)),
                ('temperature_c', models.FloatField(default=25)),
                ('energy_kwh', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_data', to='factory.machine')),
            ],
        ),
    ]
