# Generated by Django 6.1.1 on 2026-09-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0005_machinetelemetry'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='production_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='machine',
            name='production_unit',
            field=models.CharField(default='units/hour', max_length=50),
        ),
    ]
