# Generated by Django 6.1.1 on 2026-09-17 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0006_machine_production_rate_machine_production_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='flow_type',
            field=models.CharField(choices=[('MATERIAL', 'Material Flow')], default='MATERIAL', max_length=30),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_type',
            field=models.CharField(choices=[('CNC', 'CNC'), ('PRESS', 'Press'), ('CONVEYOR', 'Conveyor'), ('HVAC', 'HVAC'), ('ROBOT_ARM', 'Robot Arm'), ('COMPRESSOR', 'Compressor'), ('WELDING', 'Welding'), ('PACKAGING', 'Packaging')], max_length=30),
        ),
        migrations.AlterField(
            model_name='machinetelemetry',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='factory.machine'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('target_quantity', models.FloatField(default=0)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='factory.factory')),
            ],
        ),
        migrations.CreateModel(
            name='MachineCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_rate', models.FloatField(default=0)),
                ('production_unit', models.CharField(default='units/hour', max_length=50)),
                ('efficiency', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capabilities', to='factory.machine')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_capabilities', to='factory.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_type', models.CharField(max_length=30)),
                ('required_quantity', models.FloatField(default=0)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='factory.product')),
            ],
        ),
    ]
